### ISSUE TITLE
Authentication not working

### ISSUE THREAD

**Issue by Paarmita** [JessicaML/ScienceMotions-rails#15]
When I tried to log in the application then I was not been able to authenticate myself and an error popped up.

For more information on the error please see attached screenshot.
![screenshot from 2018-04-17 16-51-59](https://user-images.githubusercontent.com/26546816/38867071-8e67f500-4260-11e8-932d-38920c3ef67a.png)

**Comment by Paarmita** [comment]
@JessicaML The issue can be resolved by making use of this command `heroku run rake db:migrate`

**Comment by JessicaML** [comment]
Hi Paarmita, it's up again now. I had to use a bit of a hack to get it up and running again, using config.eager_load = false in config/environments/production.rb. We are still working on getting the db migrated onto Heroku but will let you know when its fixed!

**Comment by JessicaML** [comment]
@Paarmita this was solved by adding config.secret_key = ENV['SECRET_KEY_BASE'] if Rails.env.production? -> a secret key for devise on production
