### ISSUE TITLE
Migrate UI from static site

### ISSUE THREAD

**Issue by JessicaML** [JessicaML/ScienceMotions-rails#2]

**Comment by JessicaML** [comment]
rails guide: http://guides.railsgirls.com/design

**Comment by Paarmita** [comment]
@JessicaML I could migrate the index.html page from[ ScienceMotion- static](https://github.com/JessicaML/ScienceMotion-Static/blob/master/index.html) firstly and then other pages.

**Comment by JessicaML** [comment]
Yes, that would be great. Thank you!

**Comment by JessicaML** [comment]
Have you cloned and run the app locally ok?

**Comment by Paarmita** [comment]
@JessicaML  Yeah

**Comment by JessicaML** [comment]
@Paarmita I'm in the process of setting up react, so I will get in touch when that has finished! And we can start with react tasks :)
