### ISSUE TITLE
enable users to set a lesson as complete

### ISSUE THREAD

**Issue by JessicaML** [JessicaML/ScienceMotions-rails#6]

**Comment by Paarmita** [comment]
@JessicaML Can I work on this function. In order to set a lesson as complete by the user, we need lesson_id and user_id both and not keep user_id as optional?

**Comment by JessicaML** [comment]
Paarmita! actually I am in the middle of this one. Sorry

**Comment by Paarmita** [comment]
@JessicaML No problem, I will work on the other issue.
